import type { PropType } from "vue";
export const videoEmits = [
  "loadstart",
  "play",
  "pause",
  "playing",
  "seeking",
  "seeked",
  "waiting",
  "durationchange",
  "progress",
  "canplay",
  "timeupdate",
  "ended",
  "error",
  "stalled",
];
export const defineProps = {
  width: { type: String, default: "800px" },
  height: { type: String, default: "450px" },
  color: { type: String, default: "#409eff" },
  src: { required: true, type: String, default: "" },
  title: { type: String, default: "" },
  type: { type: String, default: "video/mp4" },
  poster: { type: String, default: "" },
  webFullScreen: { type: Boolean, default: false },
  speed: { type: Boolean, default: true },
  currentTime: { type: Number, default: 0 },
  playsinline: { type: Boolean, default: false },
  muted: { type: Boolean, default: false },
  speedRate: {
    type: Array,
    default: () => ["2.0", "1.5", "1.25", "1.0", "0.75", "0.5"],
  },
  autoPlay: { type: Boolean, default: false },
  loop: { type: Boolean, default: false },
  mirror: { type: Boolean, default: false },
  ligthOff: { type: Boolean, default: false },
  volume: { type: [String, Number], default: 0.3 },
  control: { type: Boolean, default: true },
  controlBtns: {
    type: Array as PropType<Array<string>>,
    default: [
      "audioTrack",
      "quality",
      "speedRate",
      "volume",
      "setting",
      "pip",
      "pageFullScreen",
      "fullScreen",
    ],
  },
  preload: { type: String, default: "auto" },
};
